version: '3.5'

services:

  jenkins:
    build:
      context: .
    container_name: 'jenkins_instance'
    ports:
    - target: 8080
      published: 8080
    env_file: ./configs/runtime.env
    volumes:
      - type: bind
        source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
        read_only: true
      - type: bind
        source: './jenkins_home/'
        target: '/var/jenkins_home/'
    tty: true
